// Mocks generated by Mockito 5.4.6 from annotations
// in crewmeister_frontend_coding_challenge/test/features/absences/data/repositories/absence_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:crewmeister_frontend_coding_challenge/features/absences/data/datasources/absences_local_file_data_source.dart'
    as _i2;
import 'package:crewmeister_frontend_coding_challenge/features/absences/data/models/absence_model.dart'
    as _i4;
import 'package:crewmeister_frontend_coding_challenge/features/absences/data/models/member_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AbsencesLocalFileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbsencesLocalFileDataSource extends _i1.Mock
    implements _i2.AbsencesLocalFileDataSource {
  @override
  _i3.Future<List<_i4.AbsenceModel>> getAbsences() =>
      (super.noSuchMethod(
            Invocation.method(#getAbsences, []),
            returnValue: _i3.Future<List<_i4.AbsenceModel>>.value(
              <_i4.AbsenceModel>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.AbsenceModel>>.value(
              <_i4.AbsenceModel>[],
            ),
          )
          as _i3.Future<List<_i4.AbsenceModel>>);

  @override
  _i3.Future<List<_i5.MemberModel>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i3.Future<List<_i5.MemberModel>>.value(
              <_i5.MemberModel>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i5.MemberModel>>.value(
              <_i5.MemberModel>[],
            ),
          )
          as _i3.Future<List<_i5.MemberModel>>);
}
